apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: demo-mongodb-sharded-cluster-1
  namespace: mongodb
spec:
  members: 3
  version: 7.0.12-ent
  type: ShardedCluster
  # security:
  #   authentication:
  #     enabled: true
  #     modes: ["SCRAM"]
  opsManager:
    configMapRef:
      # Must match metadata.name in ConfigMap file
      name: my-project
  credentials: organization-secret
  persistent: true
  # podSpec:
  #   podTemplate:
  #     spec:
  #      containers:
  #       - name: mongodb-enterprise-database
  #         resources:
  #           limits:
  #             cpu: 2
  #             memory: 1.5G
  #           requests:
  #             cpu: 1
  #             memory: 1G
  #           persistence:
  #             single:
  #               storage: 10Gi
  shardSpecificPodSpec:
  - podTemplate: # applies for the shard index 0 
      spec: 
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: 2
                memory: 1.5G
              requests:
                cpu: 1
                memory: 1G
  - podTemplate: # applies for the shard index 1
      spec:
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: 2
                memory: 1.5G
              requests:
                cpu: 1
                memory: 1G
  - podTemplate: # applies for the shard index 2
      spec:
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: 2
                memory: 1.5G
              requests:
                cpu: 1
                memory: 1G
